version: "3.9"

services:

  postgres:
#    container_name: diplom_db
    image: postgres:14.6-alpine
#    restart: always
    volumes:
      - postgres_data_pn:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 5

#  api:
##    container_name: diplom_api
#    build: .
##    restart: always
#    env_file:
#      - .env
#    environment:
#      DB_HOST: postgres
#    depends_on:
#      postgres:
#        condition: service_healthy
#    ports:
#      - "8000:8000"
##    volumes:
##      - ./todolist/:/app/todolist
#
#  collect_static:
#    build: .
#    env_file:
#      - .env
#    environment:
#      DB_HOST: postgres
#    depends_on:
#      postgres:
#        condition: service_healthy
#      api:
#        condition: service_started
#    command: python3 manage.py collectstatic -c --no-input
#    volumes:
#      - django_static:/app/static
#
#  bot:
#    build: .
#    env_file:
#      - .env
#    environment:
#      DB_HOST: postgres
#    depends_on:
#      postgres:
#        condition: service_healthy
#      api:
#        condition: service_started
#    command: python3 manage.py runbot
#
#  front:
#    image: sermalenk/skypro-front:lesson-38
##    restart: always
#    ports:
#      - "80:80"
#    depends_on:
#      api:
#        condition: service_started
#      collect_static:
#        condition: service_completed_successfully
#    volumes:
#      - django_static:/usr/share/nginx/html/static
#      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data_pn:
#  django_static:
