# Generated by Django 4.1.7 on 2023-03-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('house', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Адрес email')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release_date', models.DateField(auto_now_add=True, verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('debts', models.FloatField(default=0.0, verbose_name='Долг')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Завод-производитель'), (1, 'Ретейлер'), (2, 'Индивидуальный предприниматель')], verbose_name='Роль предприятия\\ИП')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goods.contact', verbose_name='Контактная информация')),
                ('products', models.ManyToManyField(related_name='Товары', to='goods.product')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
